services:
  app:
    build: .
    deploy:
      replicas: 3
    networks:
      - backend
      - proxy
    depends_on:
      - db

  reverse-proxy:
    image: nginx:1.27
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./reverse-proxy.conf:/etc/nginx/templates/default.conf.template
    networks:
      - proxy
    depends_on:
      - app
      - static

  db:
    image: redis:7
    restart: unless-stopped
#    ports: pas besoin de l'exposé a l'extérieur
#      - '6379:6379'
    volumes:
      - data_redis:/data
    networks:
      - backend

  static:
    image: nginx:1.27
    volumes:
      - ./assets:/usr/share/nginx/html
    networks:
      - proxy
#    ports:
#      - "81:80"

volumes:
  data_redis:

networks:
  backend:
  proxy:

